- README.md
This PR fixes the jitpack icon URL in the documentation.
- Fixed broken link (non-breaking change)
[ENG-5715]: https://neuro-id.atlassian.net/browse/ENG-5715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ENG-5715 fix jitpack icon

- .github/workflows/github-actions-master-push-assamble.yml
I somehow changed the github-actions-master-push-assemble.yml script to point to develop instead of master. The intention was to change this on my fork of neuroid-android-sdk but I think I specified the incorrect origin during the push. Not sure how I was able to push the change directly to master without a PR though. This PR here will fix that.
> revert accidental push change from master to develop back to master

- NeuroID/src/main/java/com/neuroid/tracker/service/NIDServiceTracker.kt
- app/src/androidTest/java/com/sample/neuroid/us/NeuroIdUITest.kt
HTTP retry logic added to sendEventToServer() added by @cometman. 3 tries will be done and log will be posted in the logcat as errors if errors occur (error is an http response code that is not a 200). A test will be added as a fast follow to take care of testing this in the SDK level.
> ENG-5389/packet retry

- NeuroID/src/androidLib/java/com/neuroid/tracker/callbacks/NIDActivityCallbacks.kt
- NeuroID/src/androidLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
- NeuroID/src/debug/java/com/neuroid/tracker/NeuroID.kt
- NeuroID/src/main/java/com/neuroid/tracker/utils/NIDTextWatcher.kt
- NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
- NeuroID/src/release/java/com/neuroid/tracker/NeuroID.kt
Remove and add only our text watchers to the edit text fields that are registered.
Need to look at event callbacks in NIDActivityCallbacks/NIDFragmentCallbacks later to figure out how to the not double register ui widgets.
> ENG 5952 fix edit text update

- .github/workflows/github-actions-push-assamble.yml
- .github/workflows/github-actions-tag-assamble.yml
Updating staging workflow to trigger on merge to main (except on release). This will update the sandbox app every time. Added automated release notes to workflow.
> update staging workflow and release notes

- NeuroID/src/main/java/com/neuroid/tracker/utils/NIDTextWatcher.kt
- NeuroID/src/reactNativeLib/java/com/neuroid/tracker/callbacks/NIDActivityCallbacks.kt
- NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
The fix for RN is to uncomment out the line we removed in the Android Native SDK because it was causing double event registration, however because of how RN creates/destroys activities we have to put this back in to capture all the changes when a user goes to a new page. If you have more questions lmk
> ENG-6208 - Observe changes in activity children

- NeuroID/src/reactNativeLib/java/com/neuroid/tracker/callbacks/NIDActivityCallbacks.kt
Re-registering the window listeners in the forceStart() on whatever widgets are currently available on the screen at the time will send back the touch, blur and focus events. This has to be done on startup of every screen in the ReactNative end.
> ENG 6219 add back window events

- NeuroID/src/debug/java/com/neuroid/tracker/NeuroID.kt
- NeuroID/src/main/java/com/neuroid/tracker/utils/NIDVersion.kt
- NeuroID/src/release/java/com/neuroid/tracker/NeuroID.kt
A lot of noise in this PR because I moved the `createMobileMetadata` event down to be close to where it is being called. The only real changes are:
- Adding `isRN` bool var to the NeuroID Class
- Adding `setIsRN` method to mark `isRN` as true
- Using isRN in the `getSDKVersion` method
- Appending a `isRN` key/value to the mobile metadata event
> ENG-6239 - Add isRN var and methods to use it

- NeuroID/build.gradle
- NeuroID/src/androidLib/java/com/neuroid/tracker/callbacks/NIDActivityCallbacks.kt
- NeuroID/src/reactNativeLib/java/com/neuroid/tracker/callbacks/NIDActivityCallbacks.kt
- move the implementation from onActivityPostCreated to onActivityStarted in android lib and react native activity callbacks 
- change min target to 21 in NeuroID module
- cleanup
To test this
- Create a simulator with an API 21 image. To do this go to Android Studio, tools-> device manager and click on the "Create Device" button. In the pop up choose a hardware profile (Pixel 2 is fine) and click next. Click on the Arm Images tab, scroll the table to an API level 21 system image and click the download icon in the first column (Release Name) to download the image. If the download icon is not there, you already have the image downloaded. Highlight the row, click next and click finish. You don't need to set anything else after you have chosen a system image. You simulator can now be chosen …
> ENG-6273 remove API 29 calls 

- NeuroID/src/advancedDeviceAndroidLib/java/com/neuroid/tracker/extensions/AdvancedDeviceExtension.kt
- NeuroID/src/advancedDeviceAndroidLib/java/com/neuroid/tracker/utils/FPJSHelper.kt
- NeuroID/src/advancedDeviceReactNativeLib/java/com/neuroid/tracker/extensions/AdvancedDeviceExtension.kt
- NeuroID/src/advancedDeviceReactNativeLib/java/com/neuroid/tracker/utils/FPJSHelper.kt
- NeuroID/src/main/java/com/neuroid/tracker/models/NIDEventModel.kt
- NeuroID/src/main/java/com/neuroid/tracker/storage/NIDDataStoreManager.kt
- NeuroID/src/main/java/com/neuroid/tracker/storage/NIDSharedPrefsDefaults.kt
If an FPJS key exists for the application, the request ID will be fetched from cache if its not expired. Else it will refresh the id.
> ENG-6460-caching Request id for 24 hrs

- NeuroID/src/main/java/com/neuroid/tracker/service/NIDAdvKeyService.kt
update url again in adv key service
`https://receiver.neuroid.cloud/a/hdasklghdklasgasd `
returns 
` {"message":"Forbidden"}`
> update url again in adv key service

- .github/workflows/github-actions-unit-test.yml
- NeuroID/src/advancedDeviceAndroidLib/java/com/neuroid/tracker/extensions/AdvancedDeviceExtension.kt
- NeuroID/src/advancedDeviceAndroidLib/java/com/neuroid/tracker/utils/FPJSHelper.kt
- NeuroID/src/testAdvancedDeviceAndroidLib/java/com/neuroid/tracker/FPJSHelperTest.kt
Small refactor to pass in required classes (prefs, logger and data store) into the FPJSHelper so these could be mocked in the tests. 
The tests required creating a mock FPJS client to call the success listener and the failure listener to run the success and failure modes in the FPJS.createRequestIdEvent().
> Eng 6482 unit test request id cache

- NeuroID/src/main/java/com/neuroid/tracker/utils/NIDTextWatcher.kt
Fixes the multiple copy/past problem when a user has a populated clipboard and then hit delete. The SDK will send paste events in this case for each deletion that occurs. The fix is to check that the item pasted is not empty before we send a paste event back to the server. 
Tests will be forthcoming in another PR. Thanks.
> ENG-6643 fix to not send copy/paste event 

- NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
- NeuroID/src/main/java/com/neuroid/tracker/service/NIDJobServiceManager.kt
- NeuroID/src/main/java/com/neuroid/tracker/utils/Constants.kt
- NeuroID/src/test/java/com/neuroid/tracker/NIDJobServiceManagerTest.kt
- NeuroID/src/test/java/com/neuroid/tracker/NeuroIDClassUnitTests.kt
This fix is for a crash that was found during sample app testing. 
If user calls startSession("bad session id") with a bad session id, then calls stopSession(), app will crash because the job manager was never initialized with the proper endpoint (empty) and will try to flush the empty queue causing retrofit to throw an invalid URL exception. To fix this, we statically set the URL to always point to production. This way it will always be set and the call to stopSession() will harmlessly flush an empty queue. 
Also the NeuroID.userID member variable was not being updated when the startSession("") was invoked with an empty id parameter causing getUserID() to return empty. This should have been updated with a random id. The user id was however being updated in the shared prefs and being sent …
> ENG-6920 use new session commands fix

- NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
Fix pauseCollection and resumeCollection concurrency issue. See ENG-6957 ticket for details. 
https://neuro-id.atlassian.net/browse/ENG-6957
This is a quick run of the session methods in this order (instrumented build with log)
startSession() calls resumeCollection() internally. 
```
NeuroID.getInstance()?.startSession("gsdagasdgsd");
println("kurt_test ${NeuroID.getInstance()?.isStopped()}")
NeuroID.getInstance()?.pauseCollection()
NeuroID.getInstance()?.pauseCollection()
NeuroID.getInstance()?.pauseCollection()
NeuroID.getInstance()?.pauseCollection()
println("kurt_test ${NeuroID.getInstance()?.isStopped()}")
NeuroID.getInstance()?.resumeCollection()
println("kurt_test ${NeuroID.getInstance()?.isStopped()}")
// startSession()
2024-01-12 13:08:28.389 1 kurt_test no completion handler …
```
> ENG-6957 fix pauseCollection and resumeCollection concurrency issue

- .github/workflows/github-actions-master-push-assamble.yml
In the recent prod deploy the latest tag used to deploy sandbox apps were not the latest since the branch checked out was the release PR. Adding a fix to checkout the main branch and its related tags.
> ENG-6176-checkout master branch to get the latest tag

- NeuroID/src/advancedDeviceLib/java/com/neuroid/tracker/extensions/AdvancedDeviceExtension.kt
- NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
- NeuroID/src/main/java/com/neuroid/tracker/events/TouchEventManager.kt
- NeuroID/src/main/java/com/neuroid/tracker/service/NIDNetworkListener.kt
- NeuroID/src/main/java/com/neuroid/tracker/utils/NIDTextWatcher.kt
- NeuroID/src/test/java/com/neuroid/tracker/NIDNetworkListenerTest.kt
- NeuroID/src/test/java/com/neuroid/tracker/NeuroIDClassUnitTests.kt
startSession in advanced library fix to allow null sessionID in startSession
change delay interval from 10s to 2s in network listener 
removed text watch debug` logger.d(msg = "Activity - after text $sequence")`
Don't allow resume to be called if SDK has not been started
change log level to debug for TouchEvent items.
> ENG-7467 various bug fixes, android

- NeuroID/src/advancedDeviceLib/java/com/neuroid/tracker/service/NIDAdvancedDeviceNetworkService.kt
- NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
- NeuroID/src/main/java/com/neuroid/tracker/models/NIDRemoteConfig.kt
- NeuroID/src/main/java/com/neuroid/tracker/service/NIDApiService.kt
- NeuroID/src/main/java/com/neuroid/tracker/service/NIDConfigurationService.kt
- NeuroID/src/main/java/com/neuroid/tracker/service/NIDEventSender.kt
- NeuroID/src/main/java/com/neuroid/tracker/service/NIDJobServiceManager.kt
- NeuroID/src/main/java/com/neuroid/tracker/service/NIDResponseCallBack.kt
- NeuroID/src/main/java/com/neuroid/tracker/service/RetrySender.kt
- NeuroID/src/main/java/com/neuroid/tracker/storage/NIDDataStoreManager.kt
- NeuroID/src/main/java/com/neuroid/tracker/utils/Constants.kt
- NeuroID/src/main/java/com/neuroid/tracker/utils/RetrofitInstantiator.kt
- NeuroID/src/test/java/com/neuroid/tracker/service/NeuroIDSendEventTest.kt
- app/src/androidTest/java/com/sample/neuroid/us/MockServerTest.kt
Corrected branch name just now.
Update the app to use the client key: "key_live_IjLua9hEui4X5SlhlqFomaXE" to pull the the remote config from S3. If the app cannot pull the config for any reason, the app will default to the following config: 
```
data class NIDRemoteConfig(
@SerializedName(value="call_in_progress")
val callInProgress: Boolean = true,
@SerializedName(value="event_queue_flush_interval")
val eventQueueFlushInterval: Long = 10,
@SerializedName(value="event_queue_flush_size")
val eventQueueFlushSize: Int = 1999,
@SerializedName(value="geo_location")
val geoLocation: Boolean = true,
@SerializedName(value="gyro_accel_cadence")
val gyroAccelCadence: Boolean = false,
@SerializedName(value="gyro_accel_cadence_time")
val gyroAccelCadenceTime: Long = 200L, …
```
> ENG 7530 remote config

- NeuroID/src/main/java/com/neuroid/tracker/service/NIDJobServiceManager.kt
Send Log Event indicating the sendEventsNow() failed due to some error (either server or no network). Event will be saved and sent when the server/network is available and the buffer is not full. 
from proxy after network is restored and events are sent to server: 
`,"m":"network failure, sendEventsNow() failed retrylimitHit: Unable to resolve host \"receiver.neuro-dev.com\": No address associated with hostname -1","ts":1712010263592,"type":"LOG"`
> ENG-6882 save LOG event when sendEventsNow fail.

- NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
- app/src/androidTest/java/com/sample/neuroid/us/ComponentsTest.kt
- app/src/androidTest/java/com/sample/neuroid/us/MockServerTest.kt
- app/src/androidTest/java/com/sample/neuroid/us/SandBoxTest.kt
initialize integration tests to use dev script endpoints before running tests.
> ENG-7530 update integration tests to use dev script endpoints

- NeuroID/build.gradle
- NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
- NeuroID/src/main/java/com/neuroid/tracker/utils/Constants.kt
- NeuroID/src/test/java/com/neuroid/tracker/NeuroIDClassUnitTests.kt
- app/src/main/java/com/sample/neuroid/us/MyApplicationDemo.kt
There is a bug in our test code where the setTestURL is not running on initialize when the NeuroID instance is built. This fix ensures that the proper environment is set before the remote config is pulled during unit test run. Setting the config in @Before in the integration test is too late. The remoteConfig is already pulled. The remote config is pulled on init() in NeuroID right after the constructor. 
Our customers will not need to  make changes to their code because the production environment is set as default.
> ENG-7530, set environment earlier

- NeuroID/src/main/java/com/neuroid/tracker/service/NIDJobServiceManager.kt
Move channel creation before starting the job service. This allows the startService to have an instance of Channel to call methods on. 
java.lang.NullPointerException: Attempt to invoke interface method 'kotlinx.coroutines.channels.ChannelIterator kotlinx.coroutines.channels.Channel.iterator()' on a null object reference
> ENG-7738 move channel instance creation before starting service

- NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
- NeuroID/src/main/java/com/neuroid/tracker/NeuroIDPublic.kt
- NeuroID/src/main/java/com/neuroid/tracker/events/NIDConstants.kt
- NeuroID/src/main/java/com/neuroid/tracker/models/NIDEventModel.kt
- NeuroID/src/test/java/com/neuroid/tracker/NeuroIDClassUnitTests.kt
When a user attempts a login, send an attempted login event. The ATTEMPTED_LOGIN event JSON is shown below when `NeuroID.attemptedLogin()` is called. 
```
{
"accel": {
"x": 1.4117653,
"y": 7.8197446,
"z": 6.9116683
},
"gyro": {
"x": 0.11193776,
"y": -0.4395046,
"z": -0.03191677
},
"ts": 1713937081132,
"type": "ATTEMPTED_LOGIN",
"uid": "891896486"
},
```
> ENG 7735 login attempt tracking

- .github/workflows/github-actions-master-push-assamble.yml
- .github/workflows/github-actions-push-assamble.yml
- .github/workflows/github-actions-tag-assamble.yml
- .github/workflows/github-actions-unit-test.yml
Adding advanced Native Android and RN libs to the assets released. 
Changed unit test runner to ubuntu-latest since there were errors running the emulator action `ReactiveCircus/android-emulator-runner@v2` on mac os.
> ENG-7840-adding adv libs to release

- NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
- NeuroID/src/main/java/com/neuroid/tracker/utils/NIDMetaData.kt
Moved the LocationService out of NIDMetaData by moving the instance of LocationService out of the NIDMetaData from the constructor and instead passing in the LocationService dependency into getLastKnownLocation() directly. When the NIDMetaData is serialized by Gson.toJson(), the LocationService class info will not be serialized and the serialization call will not fail with the stack overflow error as seen earlier.  First launch data packet request not containing the LocationService class info is below: 
```
{
"siteId": "",
"userId": "fghdhd",
"clientId": "f0b920b6-13aa-4be5-ae32-7649af542c10",
"identityId": "fghdhd",
"registeredUserId": "",
"pageTag": "com.neuroid.example.PersonalInformation",
"pageId": "mobile",
"tabId": "mobile",
"responseId": "98917b2e-ca58-4adf-b7cb-bc97005f62a1", …
```
> ENG-7873 move LocationService out of NIDMetaData

- NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
This was not done in the previous Network service PR (ENG-6428). ENG-7716 (FPJS latency reporting) needs this to send back FPJS latency data (connection type) if the app just started and the network config did not change.
ENG-7716 (FPJS latency reporting) is based on this branch.
> ENG-6428 update network info on startup

- NeuroID/src/main/java/com/neuroid/tracker/service/LocationService.kt
On API 21 devices, the location service will try to invoke the onStatusChanged() method in the LocationListener. The onStatusChanged() was deprecated in API 29 and not invoked in devices at or above API29 however in testing on an API21 device, it is invoked cause the exception show below: 
`java.lang.AbstractMethodError: abstract method "void android.location.LocationListener.onStatusChanged(java.lang.String, int, android.os.Bundle)"`
To fix this we use the LocationListenerCompat which will avoid the need to implement the onStatusChanged() method for all API version down to 21. The docs specify this below: 
https://developer.android.com/reference/android/location/LocationListener
```Note that this method only has a default implementation on Android R and above, and this method must still …
```
> ENG-8167 api 21 crash fix

- NeuroID/src/main/java/com/neuroid/tracker/service/NIDSessionService.kt
- NeuroID/src/test/java/com/neuroid/tracker/service/NIDSessionServiceTest.kt
Check if the SDK is already started(). If so, exit immediately. This will stop the starting of multiple data manager queues that might be occurring right now if start() is called twice in a row without stopping.
> ENG-8175 check if started and exit start() if so. fix unit tests

- NeuroID/src/main/java/com/neuroid/tracker/utils/UtilExt.kt
- NeuroID/src/test/java/com/neuroid/tracker/NeuroIdUnitTest.kt
generated user ids will now include a "mid-" prefixed to them.
> ENG-8301 prefix "nid-" to the generated user ids.

- NeuroID/src/main/java/com/neuroid/tracker/events/RegistrationIdentificationHelper.kt
- NeuroID/src/main/java/com/neuroid/tracker/extensions/NIDViewsExtensions.kt
- NeuroID/src/main/java/com/neuroid/tracker/models/NIDEventModel.kt
- NeuroID/src/test/java/com/neuroid/tracker/AndroidTestUtils.kt
- NeuroID/src/test/java/com/neuroid/tracker/events/NIDIdentityAllViewsTest.kt
Element is registered from the `MyFragment` callback, but now the screen hierarchy shows where the element truly is from (I.e. `childFragment`)
Updated Event Example
```
EVENT: REGISTER_TARGET - childFrag1Email - 
et=Edittext::AppCompatEditText,
rts=null, 
ec=AppInit 
v=S~C~~0
tg={
attr=[
{n=guid, v=27f312bd-5d77-354a-b7ed-ec059a07ff9e}, 
// THIS IS THE IMPORTANT PIECE
{n=screenHierarchy, v=/com.neuroid.example.Login/com.neuroid.example.MyFragment/com.neuroid.example.ChildFragment1/childFrag1Email}
{n=top-screenHierarchy, v=/MyFragment/childFrag1Email},
{n=parentClass, v=MyFragment}
,{n=component, v=fragment}, {}]}
```
> ENG-8375 - Update Screen Hierarchy Logic

- NeuroID/build.gradle
- NeuroID/src/main/java/com/neuroid/tracker/storage/NIDDataStoreManager.kt
- NeuroID/src/main/java/com/neuroid/tracker/utils/VersionChecker.kt
- NeuroID/src/test/java/com/neuroid/tracker/storage/NIDDataStoreManagerUnitTests.kt
This PR is to mitigate a crash that MGI is currently seeing in our 3.3.2 SDK. it is only happening on the Samsung S22 device in QE testing however that might just be coincidental and could probably happen to all devices. 
What we think is happening is a race condition where the isFullBuffer() method will check if the event list is empty, then the job manager will context switch to clear the event list calling swapEvents() then context switch back to isFullBuffer() which will call eventList.last() to get the last type, see it is empty and throw the exception below that MGI QE is seeing. To mitigate this, we Synchronize the isFullBuffer() method so it will complete execution without being context switched and add a try/catch to catch the exception and handle it if it happens anyway to …
> ENG-8497 mitigate crash when MutableList.last() is called when empty

- NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
- NeuroID/src/test/java/com/neuroid/tracker/NeuroIDClassUnitTests.kt
- NeuroID/src/test/java/com/neuroid/tracker/service/NIDSessionServiceTest.kt
Remove extra set activity lifecycle callback, let the setNeuroIDInstance() handle it. 
There is bug that will allow setting the Activity lifecycle callback handler without setting the NeuroID instance to the singleton if builder is called more than once. This might be causing situations where EditText fields are not sending back input events to our server. The callback handler will have a handle to the new job manager to send back events which does not exist and will silently error out because of a check that will not set the new NeuroID instance to the singleton. This will happen only on multiple calls to Builder.build().
> ENG-8564 remove extra set activity lifecycle callback

- NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
- NeuroID/src/main/java/com/neuroid/tracker/service/NIDEventSender.kt
- NeuroID/src/main/java/com/neuroid/tracker/utils/NIDMetaData.kt
- app/build.gradle
- testapp/build.gradle
Add last app install time in metadata event. The change will look like this: 
```
"metadata": {
"batteryLevel": 99,
"brand": "google",
"carrier": "",
"device": "sunfish",
"display": "TQ3A.230805.001.S2",
"displayResolution": "1080,2138",
"gpsCoordinates": {
"authorizationStatus": "unknown",
"latitude": -1.0,
"longitude": -1.0
},
"isJailBreak": false,
"isSimulator": false,
"isWifiOn": true,
"lastInstallTime": 1740447749466,
"manufacturer": "Google",
"model": "Pixel 4a",
"osVersion": "33",
"product": "sunfish",
"totalMemory": 5.472507476806641
},
```
> ENG-9331 add last app install time in metadata

- NeuroID/build.gradle
Remove source jar from release builds (Android SDK , ReactNative). The debug builds retain source. 
```
➜  ~ cd .m2/repository/com/neuroid/android-sdk
➜  android-sdk ls
"3.5.2"                  maven-metadata-local.xml
➜  android-sdk cd \"3.5.2\" 
➜  "3.5.2" ls
android-sdk-"3.5.2".aar    android-sdk-"3.5.2".module android-sdk-"3.5.2".pom
➜  "3.5.2" cd ..
➜  android-sdk ls
"3.5.2"                  maven-metadata-local.xml
➜  android-sdk cd ..
➜  neuroid ls
android-sdk             android-sdk-debug       react-android-sdk       react-android-sdk-debug
➜  neuroid cd react-android-sdk  
➜  react-android-sdk ls
"3.5.2"                  maven-metadata-local.xml
➜  react-android-sdk cd \"3.5.2\" 
➜  "3.5.2" ls
react-android-sdk-"3.5.2".aar    react-android-sdk-"3.5.2".module …
```
> ENG-9436 remove source jar from release builds (android and react native)

- NeuroID/build.gradle
- NeuroID/proguard-rules.pro
Enable obfuscation on Android SDK release builds. 
The GSON version was updated to 2.11 that fixes ProGuard issues with TypeToken usage in AdvancedDeviceIDManager.
Tested on Layout sample app with Compose Login screen and the existing Integration sample app.
Below is the contents of the classes . As you can see below the classes have been obfuscated except for classes that are accessed directly by host apps or classes that are accessed via reflection (serialized for use in network applications or views accessed through the activity lifecycle) . 
```
➜  "3.5.2" jar -xvf android-sdk-\"3.5.2\".aar 
inflated: R.txt
inflated: AndroidManifest.xml
inflated: classes.jar
inflated: proguard.txt
inflated: META-INF/com/android/build/gradle/aar-metadata.properties
➜  "3.5.2" jar -xvf classes.jar …
```
> ENG-9437 obfuscation

- NeuroID/proguard-rules.pro
proguard rule update to fix crasher on APi34 and above devices.
> reuqired for API34+ otherwise crash occurs, requries another release.

- NeuroID/proguard-rules.pro
Added keep rule to not obfuscate the metadata. 
metadata without the keep rule
`"metadata": {
"a": "samsung",
"b": "r11q",
"c": "UP1A.231005.007.S711U1UES6CYC1",
"d": "samsung",
"e": "SM-S711U1",
"f": "r11quew",
"g": "34",
"h": "1080,2218",
"i": "Mint",
"j": 7.051990509033203,
"k": 100,
"l": false,
"m": true,
"n": false,
"o": {
"authorizationStatus": "unknown",
"latitude": -1.0,
"longitude": -1.0
},
"p": 1746118723134
}`
metadata with the keep rule: 
`"metadata":{"batteryLevel":100,"brand":"samsung","carrier":"Mint","device":"r11q","display":"UP1A.231005.007.S711U1UES6CYC1","displayResolution":"1080,2218","gpsCoordinates":{"authorizationStatus":"unknown","latitude":-1.0,"longitude":-1.0},"isJailBreak":false,"isSimulator":false,"isWifiOn":true,"lastInstallTime":1746118723134,"manufacturer": …
> ENG-9942 add keep to stop obfuscation of the metadata

- NeuroID/src/reactNative/java/com/neuroid/tracker/extensions/NIDRNBuilder.kt
- NeuroID/src/testReactNative/java/com/neuroid/tracker/extensions/NIDRNBuilderTest.kt
Pass ReactNative set advancedDeviceKey to the native NeuroID configuration.
> ENG-10215, pass ReactNative set advancedDeviceKey to native

- .github/workflows/github-actions-unit-test.yml
- NeuroID/build.gradle
- NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
- sonar-project.properties
Make sure that coverage numbers show up in sonar. 
When code is added, the coverage numbers are calculated. Example, add this line to NeuroID.kt and sonar will report 60% coverage on the changed file. 
```
// testing coverage, remove after tests complete, do not merge
if (isAdvancedDevice) {
captureEvent(type = LOG, m = "Advanced Device Key: $advancedDeviceKey", level = "INFO")
}
```
> ENG-10540 add coverage to sonar
