.github/workflows/github-actions-assamble.yml
NeuroID/build.gradle

Adding action to create a release version

Action Release

---

.github/workflows/github-actions-unit-test.yml
NeuroID/src/main/java/com/neuroid/tracker/service/NIDServiceTracker.kt
NeuroID/src/main/java/com/neuroid/tracker/storage/NIDSharedPrefsDefaults.kt
app/src/androidTest/java/com/sample/neuroid/us/NIDTestConstants.kt
app/src/androidTest/java/com/sample/neuroid/us/NeuroIdUITest.kt

- Update Create Session UI Tests

Version 1.0

---

NeuroID/src/androidLib/java/com/neuroid/tracker/NeuroID.kt
NeuroID/src/androidLib/java/com/neuroid/tracker/callbacks/NIDFragmentCallbacks.kt
NeuroID/src/androidLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
NeuroID/src/androidLib/java/com/neuroid/tracker/utils/NIDViewsExtensions.kt
NeuroID/src/main/java/com/neuroid/tracker/callbacks/NIDActivityCallbacks.kt
NeuroID/src/main/java/com/neuroid/tracker/service/NIDServiceTracker.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/callbacks/NIDFragmentCallbacks.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDRegisterEventsHelper.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/utils/NIDViewsExtensions.kt
app/src/androidTest/java/com/sample/neuroid/us/NIDTestConstants.kt
app/src/main/java/com/sample/neuroid/us/activities/NIDCustomEventsActivity.kt
app/src/main/java/com/sample/neuroid/us/fragments/NIDOnlyOneFragment.kt

* EC value needs to be "AppInit" by default
* EC value should be set with setCurrentScreen
* Attr array should have GUID & screenHierarchy values
* screenHierarchy should end with ec value

Task | ENG 2139 - Register Target Event | Diego Maldonado

---

NeuroID/src/androidLib/java/com/neuroid/tracker/utils/NIDViewsExtensions.kt
NeuroID/src/main/java/com/neuroid/tracker/events/NIDTouchEventManager.kt

* Add random id on views without id or tag

Task | ENG-2138 - Fix Touch event  | Diego Maldonado

---

.github/workflows/github-actions-push-assamble.yml
.github/workflows/github-actions-unit-test.yml
NeuroID/build.gradle

Adding the last commit message when aar is published

[ENG-2156] Adding commit message

---

NeuroID/build.gradle
NeuroID/src/androidLib/java/com/neuroid/tracker/callbacks/NIDFragmentCallbacks.kt
NeuroID/src/androidLib/java/com/neuroid/tracker/events/NIDRegisterEventsHelper.kt
NeuroID/src/main/java/com/neuroid/tracker/callbacks/NIDActivityCallbacks.kt
NeuroID/src/main/java/com/neuroid/tracker/events/NIDTouchEventManager.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/callbacks/NIDOnLoadReactRootListener.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDRegisterEventsHelper.kt
app/src/androidTest/java/com/sample/neuroid/us/NeuroIdUITest.kt
app/src/main/java/com/sample/neuroid/us/fragments/NIDOnlyOneFragment.kt
app/src/main/res/layout/nid_fragment_only_one.xml
build.gradle

Adding validation to verify one event by test

One Event by test

---

NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDRegisterEventsHelper.kt

* Add pause on identify all views

Task | ENG-2173 | Input Events

---

NeuroID/src/androidLib/java/com/neuroid/tracker/callbacks/NIDActivityCallbacks.kt
NeuroID/src/androidLib/java/com/neuroid/tracker/callbacks/NIDFragmentCallbacks.kt
NeuroID/src/androidLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
NeuroID/src/androidLib/java/com/neuroid/tracker/events/NIDRegisterEventsHelper.kt
NeuroID/src/main/java/com/neuroid/tracker/utils/NIDTextWatcher.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/callbacks/NIDActivityCallbacks.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/callbacks/NIDFragmentCallbacks.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDRegisterEventsHelper.kt

* Fix PASTE Event
* Fix lost INPUT events

Task | Native Android SDK INPUT and PASTE Events

---

NeuroID/src/androidLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt

Adding ImageButton support

---

NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt

* Detect Buttons more efficient

Task | ENG-2188 Ambiguous tgs naming | Diego Maldonado

---

NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt

Fix | ENG 2535 duplication input | Diego Maldonado

---

NeuroID/src/androidLib/java/com/neuroid/tracker/NeuroID.kt
NeuroID/src/main/java/com/neuroid/tracker/service/NIDJobServiceManager.kt
NeuroID/src/main/java/com/neuroid/tracker/service/NIDServiceTracker.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/NeuroID.kt
app/src/androidTest/java/com/sample/neuroid/us/NeuroIdUITest.kt

[ENG-2558] Adding Configure with options

---

NeuroID/src/main/java/com/neuroid/tracker/utils/NIDTextWatcher.kt
app/src/androidTest/java/com/sample/neuroid/us/NeuroIdUITest.kt
app/src/main/java/com/sample/neuroid/us/activities/MainActivity.kt
app/src/main/res/layout/nid_activity_main.xml
app/src/main/res/values/strings.xml

Fixing duplicate inputs on ReactNative and Native Projects

[ENG-2627] Fixing duplicate inputs

---

NeuroID/src/main/java/com/neuroid/tracker/callbacks/NIDSensorHelper.kt

* Send null when no acceleromter data / gyro for x y z values

Task | ENG-2677 | Diego Maldonado

---

NeuroID/src/androidLib/java/com/neuroid/tracker/NeuroID.kt
NeuroID/src/main/java/com/neuroid/tracker/models/NIDEventModel.kt
NeuroID/src/main/java/com/neuroid/tracker/service/NIDServiceTracker.kt
NeuroID/src/main/java/com/neuroid/tracker/storage/NIDDataStoreManager.kt
NeuroID/src/main/java/com/neuroid/tracker/storage/NIDSharedPrefsDefaults.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/NeuroID.kt
app/src/androidTest/java/com/sample/neuroid/us/ComponentsTest.kt
app/src/androidTest/java/com/sample/neuroid/us/NIDTestConstants.kt
app/src/androidTest/java/com/sample/neuroid/us/NeuroIdUITest.kt
app/src/main/java/com/sample/neuroid/us/MyApplicationDemo.kt
app/src/main/java/com/sample/neuroid/us/activities/MainActivity.kt

Saving and fetching preferences on background

[ENG-2696] Preferences on background

---

NeuroID/src/reactNativeLib/java/com/neuroid/tracker/NeuroID.kt

ENG-2846 | New Parameters, environment and site id | Diego Maldonado

---

NeuroID/src/main/java/com/neuroid/tracker/utils/RootHelper.kt

Task | ENG-3022 Part 2 | Diego Maldonado

---

NeuroID/src/androidLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
NeuroID/src/main/java/com/neuroid/tracker/callbacks/NIDGlobalEventCallback.kt
NeuroID/src/main/java/com/neuroid/tracker/models/NIDEventModel.kt
NeuroID/src/main/java/com/neuroid/tracker/service/NIDServiceTracker.kt
NeuroID/src/main/java/com/neuroid/tracker/utils/NIDTextWatcher.kt

- Fixing v and hv fields on json Event
- Adding sdkVersion and jsVersion

Fixing v and hv fields on json Event

---

NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
app/src/main/java/com/sample/neuroid/us/activities/NIDCustomEventsActivity.kt
app/src/main/java/com/sample/neuroid/us/fragments/NIDOnlyOneFragment.kt

* Replace all spaces on setScreenName method with hmtl format space code (%20)

Fix | Replace spaces on setScreenName | Diego Maldonado

---

NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
NeuroID/src/main/java/com/neuroid/tracker/service/NIDJobServiceManager.kt
NeuroID/src/main/java/com/neuroid/tracker/utils/NIDVersion.kt

Adding synchronized

---

NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt

Create new methods for dynamo key

Task | ENG-3246- Add Dynamo Key | Diego Maldonado

---

NeuroID/src/androidLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/sample/neuroid/us/activities/DynamicActivity.kt
app/src/main/java/com/sample/neuroid/us/activities/MainActivity.kt
app/src/main/res/layout/nid_activity_dynamic.xml
app/src/main/res/layout/nid_activity_main.xml

[ENG-3820] Adding new views on runtime 

---

NeuroID/src/androidLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
NeuroID/src/androidLib/java/com/neuroid/tracker/utils/NIDViewsExtensions.kt
NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
NeuroID/src/main/java/com/neuroid/tracker/utils/UtilExt.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
app/src/main/java/com/sample/neuroid/us/activities/DynamicActivity.kt

[ENG-3823] Adding RegisterTarget Method

---

app/src/androidTest/java/com/sample/neuroid/us/NeuroIdUITest.kt
app/src/androidTest/java/com/sample/neuroid/us/TextUnitTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/sample/neuroid/us/activities/MainActivity.kt
app/src/main/java/com/sample/neuroid/us/fragments/NIDFirstFragment.kt
app/src/main/res/layout/nid_activity_main.xml
app/src/main/res/layout/nid_fragment_one.xml
app/src/main/res/values/strings.xml

* Make sure there is a FOCUS event before all Field inputs. Make sure there is a BLUR event AFTER input is complete.

Task | ENG-3970 - Android Integration Tests FOCUS and BLUR events | Diego Maldonado

---

.github/workflows/github-actions-release-notification.yml
app/src/androidTest/java/com/sample/neuroid/us/NeuroIdUITest.kt

Sending a slack notification on each SDK Version

Release Notification

---

.github/workflows/github-actions-master-push-assamble.yml

* Send alert to slack on failure

Task | ENG-3956 Github workflow Android SDK | Diego Maldonado

---

LICENSE

This PR creates a LICENSE file for the Android SDK.
- New file (non-breaking change)
[ENG-5704]: https://neuro-id.atlassian.net/browse/ENG-5704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENG-5704 add MIT License file

---

app/src/androidTest/java/com/sample/neuroid/us/ComponentsTest.kt
app/src/androidTest/java/com/sample/neuroid/us/NIDSchema.kt
app/src/androidTest/java/com/sample/neuroid/us/NeuroIdUITest.kt

Fix test11ValidateSwipeScreen() 
The "TOUCH_MOVE" event is not recored in the event set when a swipe action is done in the test11ValidateSwipeScreen() test method. Instead we will use "WINDOW_FOCUS" to denote the swipe. 
The validateEvents() method was simplified to do only the schema validation if the validateEvent flag is false. Originally if validateEvent flag is set false in the validateEvents() call, it will always assert true which doesn't make sense. 
Also to simplify the validate method, validate schema and validate events were separated into two methods. 
Events recorded on actual device and a simulator are show below filtering on “WINDOW_FOCUS“. 
actual device
```
{"type":"REGISTER_TARGET","tg":{"attr":[{"n":"guid","v":"5ceaa429-29e2-3ec5-a154-c11f3fd8188c"},{"n":"screenHierarchy …
```

ENG-5755 fix swipe test

---

app/src/androidTest/java/com/sample/neuroid/us/TextUnitTest.kt
app/src/androidTest/java/com/sample/neuroid/us/activities/DynamicActivityTest.kt
app/src/androidTest/java/com/sample/neuroid/us/activities/LifeCycleTest.kt
app/src/androidTest/java/com/sample/neuroid/us/activities/NonAutomaticEventsTest.kt

Missed some tests. These need to run validateSchema() as well.

ENG 5755 update rest of tests

---

.github/workflows/github-actions-master-push-assamble.yml
.github/workflows/github-actions-push-assamble.yml
.github/workflows/github-actions-update-version.yml

This is a temporary workflow that can be triggered from the UI to update the sdk version listed in version.properties file. This creates a PR which requires approvals to merge to main. This in turn will update the Reactnative and Android Sandbox apps with a direct push to main. This part of the workflow will be replaced once branch protection rules are enforced again.

ENG-5673-version release workflow

---

.github/workflows/github-actions-tag-assamble.yml

Updating to service account developer PAT.

updating to service account PAT

---

NeuroID/src/androidLib/java/com/neuroid/tracker/callbacks/NIDActivityCallbacks.kt

updated the onActivityResumed to always run the registrations. thanks Clay for the fix!

On resume test

---

.github/workflows/github-actions-master-push-assamble.yml
.github/workflows/github-actions-tag-assamble.yml

Adding debug .aar files to assets if customer requires them. Also trimming commit from version tag.

Releasing debug flavors in assets

---

NeuroID/src/debug/java/com/neuroid/tracker/NeuroID.kt
NeuroID/src/release/java/com/neuroid/tracker/NeuroID.kt

Have setScreenName() throw exception is SDK is not started

ENG-6122 have setScreenName() throw exception is SDK is not started

---

NeuroID/src/androidLib/java/com/neuroid/tracker/utils/NIDViewsExtensions.kt
NeuroID/src/test/java/com/neuroid/tracker/NeuroIdUnitTest.kt
app/src/debug/java/com/sample/neuroid/us/activities/NIDPayloadJsonActivity.kt
app/src/main/java/com/sample/neuroid/us/activities/NIDCustomEventsActivity.kt
app/src/main/java/com/sample/neuroid/us/activities/sandbox/SandBoxFragment.kt
app/src/main/java/com/sample/neuroid/us/fragments/NIDOnlyOneFragment.kt

update the getIdOrTag() to return contentDescription as the id if available in the view, else return tag, resourceEntryName or random ID.

ENG-6142 update the getIdOrTag() to return contentDescription

---

NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt

Because of how RN renders buttons (a view with either a text or image inside) we needed to specifically look for them.
NOTE: This will not capture the click/touch events that happen on said buttons as Android does not allow more than 1 click listener and RN is using that spot. But we can at least register the target so that DS can see what the page looks like
NOTE: This PR will capture basic included RN elements, however because you can install any 3rd party library for other RN components I don't know that its worth the effort to try and find every possible element and include it, especially as TextFields seem to provide the most value for DS

ENG-6220 - Add Support for RN Buttons

---

NeuroID/build.gradle
NeuroID/src/androidLib/java/com/neuroid/tracker/callbacks/NIDActivityCallbacks.kt
NeuroID/src/androidLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
NeuroID/src/androidLib/java/com/neuroid/tracker/events/NIDRegisterEventsHelper.kt
NeuroID/src/androidLib/java/com/neuroid/tracker/utils/NIDViewsExtensions.kt
NeuroID/src/debug/java/com/neuroid/tracker/NeuroID.kt
NeuroID/src/main/java/com/neuroid/tracker/callbacks/NIDGlobalEventCallback.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/callbacks/NIDActivityCallbacks.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/callbacks/NIDFragmentCallbacks.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDIdentifyAllViews.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/events/NIDRegisterEventsHelper.kt
NeuroID/src/reactNativeLib/java/com/neuroid/tracker/utils/NIDViewsExtensions.kt
NeuroID/src/release/java/com/neuroid/tracker/NeuroID.kt
NeuroID/src/test/java/com/neuroid/tracker/NIDIdentityAllViewsTest.kt
NeuroID/src/test/java/com/neuroid/tracker/NeuroIdUnitTest.kt

view registration tests and small refactor to send in logger and data source to allow mocking.
test for all widget types except the spinner, still working on this one.

ENG-6164 view registration tests 

---

NeuroID/src/main/java/com/neuroid/tracker/service/NIDAdvKeyService.kt

update url to neuro-id from neuro-dev for the adv key service API call

update url to neuro-id from neuro-dev for the adv key service API call

---

NeuroID/src/advancedDeviceAndroidLib/java/com/neuroid/tracker/extensions/AdvancedDeviceExtension.kt
NeuroID/src/advancedDeviceReactNativeLib/java/com/neuroid/tracker/extensions/AdvancedDeviceExtension.kt
NeuroID/src/main/java/com/neuroid/tracker/utils/Constants.kt

Currently only the PROD endpoint is going to be available in the sdk. The dev endpoint is only for internal testing.

ENG-6571-added FPJS endpoint environment url

---

NeuroID/src/main/java/com/neuroid/tracker/utils/Constants.kt

Using HTTPS custom endpoint while calling FPJS

ENG-6571-updating to secure HTTP protocol

---

NeuroID/src/main/java/com/neuroid/tracker/callbacks/NIDSensorHelper.kt
NeuroID/src/main/java/com/neuroid/tracker/service/NIDJobServiceManager.kt
NeuroID/src/test/java/com/neuroid/tracker/SensorHelperTests.kt

ENG 6165 sensor helper tests

---

NeuroID/src/test/java/com/neuroid/tracker/NeuroIDClassUnitTests.kt
app/src/release/java/com/sample/neuroid/us/activities/MainActivity.kt

Update call in the sample app to match sdk function `excludeViewByTestID`

ENG-6705 Update resource ID call in app

---

NeuroID/src/main/java/com/neuroid/tracker/service/NIDJobServiceManager.kt
NeuroID/src/main/java/com/neuroid/tracker/service/NIDServiceTracker.kt
NeuroID/src/test/java/com/neuroid/tracker/NIDJobServiceManagerTest.kt
NeuroID/src/test/java/com/neuroid/tracker/NeuroIDSendEventTest.kt

Add tests for the NIDJobServiceManager class. Refactor NIDJobServiceManager to allow mocking and to read internal variables to assert.

ENG-6167 add tests for the NIDJobServiceManager

---

NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
NeuroID/src/test/java/com/neuroid/tracker/NeuroIDClassUnitTests.kt

ensure that setUserID () and setRegisteredUserID() returns false and not set id if user entered ID is invalid. setStatus() however should operate as normal (set random id if user entered id in invalid/empty)

ENG-6952, fix setUserId/setRegisteredUsedID

---

NeuroID/src/main/java/com/neuroid/tracker/utils/RootHelper.kt

Add checks to look for various simulators that use x86 hardware and various other types. Tests forthcoming.

Eng 6925 make isSimulator check more robust. 

---

.github/workflows/github-actions-tag-assamble.yml

Adding target based off GH docs https://cli.github.com/manual/gh_release_create

add target branch to release

---

NeuroID/src/main/java/com/neuroid/tracker/callbacks/NIDSensorHelper.kt
NeuroID/src/main/java/com/neuroid/tracker/utils/NIDTimerActive.kt

ENG-7211 fix sensor handling

---

NeuroID/src/main/java/com/neuroid/tracker/storage/NIDDataStoreManager.kt

count both queued events and events against the 2k event count threshold

ENG-7367 count both queued events and events againts 2k count

---

NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
NeuroID/src/main/java/com/neuroid/tracker/service/LocationService.kt
NeuroID/src/main/java/com/neuroid/tracker/utils/NIDMetaData.kt
NeuroID/src/test/java/com/neuroid/tracker/service/NIDLocationServiceTest.kt

Ensure that a false location flag turns off location info in metadata.

ENG-7752 ensure location flag turns off location info in metadata

---

.github/workflows/github-actions-tag-assamble.yml

ENG-7840, remove trailing spaces in the assemble script, based from master
tested here: https://github.com/kishisaka-nid/neuroid-android-sdk-test/releases/tag/v0.1.7

ENG-7840, remove trailing spaces in the assemble script

---

.github/workflows/github-actions-tag-assamble.yml

remove trailing spaces. 
tested here: https://github.com/kishisaka-nid/neuroid-android-sdk-test/releases/tag/v0.1.7

ENG-7840 remove trailing spaces

---

NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
NeuroID/src/test/java/com/neuroid/tracker/NeuroIDClassUnitTests.kt

Also some small linting errors (redundant string interpolation)

ENG-7960 - Change isSDKStarted to be private setter/public getter

---

NeuroID/src/main/java/com/neuroid/tracker/models/NIDRemoteConfig.kt

update geolocation default remote config to false.

ENG-7902 turn off gelocation updates in default remote config

---

NeuroID/src/main/java/com/neuroid/tracker/service/NIDEventSender.kt

Prints Summary:
```
Payload Summary:
ClientID: 9677b795-109b-4f52-9ef2-bc8fe143e5c0
UserID: jhhjh
RegisteredUserID: jhhjhregistered-id
LinkedSiteID: form_bench881
TabID: mobile-nid-3215ed30-9181-4c41-be7f-0f3eafd18a63
Packet Number: 3
SDK Version: 5.android-3.3.0
Event Count: 6
Byte Count: 3539
```

ENG-8354 - Add Payload Summary Logging

---

NeuroID/src/main/java/com/neuroid/tracker/NeuroID.kt
NeuroID/src/main/java/com/neuroid/tracker/compose/JetpackCompose.kt
NeuroID/src/main/java/com/neuroid/tracker/models/NIDEventModel.kt
NeuroID/src/test/java/com/neuroid/tracker/AndroidTestUtils.kt
NeuroID/src/test/java/com/neuroid/tracker/compose/JetpackComposeTests.kt
NeuroID/src/test/java/com/neuroid/tracker/utils/NIDTextWatcherTests.kt

Fill guts of method to capture button tap. Mark events as synthetic for DS, also add metadata about being a compose event

ENG-8435 - Capture Compose Button Tap

---

NeuroID/src/main/java/com/neuroid/tracker/compose/JetpackCompose.kt

move page and element name to: 
tgs = elementName,
ec = pageName,

ENG-8434 move page and name to tgs and ec

---

NeuroID/src/advancedDeviceLib/java/com/neuroid/tracker/service/NIDAdvancedDeviceNetworkService.kt
NeuroID/src/main/java/com/neuroid/tracker/compose/JetpackCompose.kt
NeuroID/src/main/java/com/neuroid/tracker/service/NIDConfigService.kt

Add secondary track elements method, add register target event
I.E.
```
NeuroID.compose?.trackPageElements(
pageName = NewApplicationScreens.personal.name,
elements = arrayOf(
Pair(first = "First Name", second = firstName),
Pair(first = "Date of Birth", second = dob),
)
)
```

ENG-8489 - Add New method to track page and elements in one

---

build.gradle

revert build gradle to 7.2.0

---

.github/workflows/github-actions-master-push-assamble.yml
.github/workflows/github-actions-push-assamble.yml
.github/workflows/github-actions-tag-assamble.yml
.github/workflows/github-actions-unit-test.yml
NeuroID/build.gradle
NeuroID/src/test/java/com/neuroid/tracker/service/NIDJobServiceManagerTest.kt
NeuroID/src/test/java/com/neuroid/tracker/storage/NIDDataStoreManagerUnitTests.kt
NeuroID/src/testAdvancedDeviceLib/java/com/neuroid/tracker/AdvancedDeviceIDManagerServiceTest.kt
app/build.gradle
app/src/androidTest/AndroidManifest.xml
app/src/androidTest/java/com/sample/neuroid/us/ComponentsTest.kt
app/src/androidTest/java/com/sample/neuroid/us/MockServerTest.kt
app/src/androidTest/java/com/sample/neuroid/us/NeuroIdUITest.kt
app/src/androidTest/java/com/sample/neuroid/us/SandBoxTest.kt
app/src/androidTest/java/com/sample/neuroid/us/TextUnitTest.kt
app/src/androidTest/java/com/sample/neuroid/us/activities/DynamicActivityTest.kt
app/src/androidTest/java/com/sample/neuroid/us/activities/LifeCycleTest.kt
app/src/androidTest/java/com/sample/neuroid/us/activities/NonAutomaticEventsTest.kt
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Make the integration tests (in app/src/androidTest) run properly. 
Now that these are running properly, I will add a new test app with the sample layout app in another PR. Also the SDK is targeting 34 successfully. Min SDK remains at API 21 however.

ENG-8797 make integration tests run, SDK 34 update

---

NeuroID/build.gradle
build.gradle

Update FPJS to 2.5.0
Update Kotlin version to 1.9.24

ENG-7193 update FPJS lib to v2.5.0, kotlin version to 1.9.24

---

gradle/wrapper/gradle-wrapper.properties
jitpack.yml

Update gradle wrapper to 8.10.2 and use Java 17 to publish to jitpack.

Update gradle wrapper to 8.10.2 and use Java 17 to publish to jitpack. 

---

.github/workflows/github-actions-tag-assamble.yml

remove the advanced artifact upload (because these don't exist anymore) on publishing release

remove adv upload on publish

---

.github/workflows/github-actions-main-push-assamble.yml
.github/workflows/github-actions-push-assamble.yml
.github/workflows/github-actions-tag-assamble.yml
.github/workflows/github-actions-unit-test.yml
.github/workflows/github-actions-update-version.yml

Update github action scripts to use main instead of master.

ENG-5744 update github scripts to use main instead of master

---

NeuroID/build.gradle
NeuroID/src/main/java/com/neuroid/tracker/utils/VersionChecker.kt
app/build.gradle
testapp/build.gradle

increase the api target to 35 to comply with playstore policy.

ENG-10261, increase the api target to 35

---

NeuroID/build.gradle

Update FPJS library 2.10.0. readme here: 
https://dev.fingerprint.com/docs/changelog-android-sdk#v2100
Tested in sandbox app. ADV device RID successfully recevied and passed to backend.

ENG-10592 update fpjs to 2.10.0
